version: '3.8'

services:
  coremvc:
    image: coremvc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      # Connection string for SQL Server running in another container
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=CoreMVC;User Id=sa;Password=1234;TrustServerCertificate=True;"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
